{% set name = "usort" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/usort-{{ version }}.tar.gz
  sha256: 3928043b4644f35c80e417698b0e89cc7bb51a1b0a021f2ba55ceffb86326398

build:
  entry_points:
    - usort = usort.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - setuptools >=38.3.0
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - attrs >=21.2.0
    - click >=7.0.0
    - libcst >=0.3.7
    - moreorless >=0.3.0
    - stdlibs >=2021.4.1
    - tomli
    - trailrunner >=1.0,<2.0

test:
  imports:
    - usort
  commands:
    - pip check
    - usort --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/facebook/usort
  summary: A small, safe import sorter
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - dstoeckel
    - nicornk
